### ISSUE TITLE
selNSGA2 erroring trying to hash something associated with IndividualMaterial object

### ISSUE THREAD

**Issue by roddtalebi** [roddtalebi/ezCGP#209]
This started once I switch the selNSGA2 from my own custom version of the code from waaaaay back when I started ezcgp as an IRAD, to using selNSGA2 directly from the deap.tools package.

```
Traceback (most recent call last):
  File "main.py", line 176, in <module>
    main(problem_filename, problem_output_directory, args.previous_run, seed, args.loglevel)
  File "main.py", line 97, in main
    universe.run(problem)
  File "/storage/home/hpaceice1/rtalebi3/ezCGP/codes/universe.py", line 220, in run
    self.population_selection(problem)
  File "/storage/home/hpaceice1/rtalebi3/ezCGP/codes/universe.py", line 179, in population_selection
    problem.population_selection(self)
  File "/storage/home/hpaceice1/rtalebi3/ezCGP/problems/problem_definition.py", line 125, in population_selection
    universe.population.population = selections.selNSGA2(universe.population.population, self.pop_size, nd='standard')
  File "/storage/home/hpaceice1/rtalebi3/ezCGP/codes/utilities/selections.py", line 42, in selNSGA2
    return deap.tools.selNSGA2(individuals, k, nd)
  File "/storage/home/hpaceice1/rtalebi3/.conda/envs/ezcgp-py/lib/python3.7/site-packages/deap/tools/emo.py", line 34, in selNSGA2
    pareto_fronts = sortNondominated(individuals, k)
  File "/storage/home/hpaceice1/rtalebi3/.conda/envs/ezcgp-py/lib/python3.7/site-packages/deap/tools/emo.py", line 76, in sortNondominated
    map_fit_ind[ind.fitness].append(ind)
  File "/storage/home/hpaceice1/rtalebi3/.conda/envs/ezcgp-py/lib/python3.7/site-packages/deap/base.py", line 231, in __hash__
    return hash(self.wvalues)
TypeError: unhashable type: 'ezData_numpy'
```

**Comment by roddtalebi** [comment]
found this https://github.com/DEAP/deap/issues/354 which makes me think the error has to do with the fitness.values tuple being in a 'bad' datatype.

I checked it out and the fitness values printed as ```(ezData_numpy(1.39115031), ezData_numpy(3.9988233))``` so it is still a tuple BUT the actual values are ezData_numpy types which are made to also be np.ndarrays which are unhashable as per the issue. Need a way to convert those values back to floats or something but make it a universal change hopefully.
